import type { SwimExercise } from "@/lib/swim/types";

// Единственный источник данных об упражнениях VOLT Swim. Программы и интервалы
// (lib/swim/program-engine.ts) ссылаются на упражнения по id — названия,
// описания и т.д. нигде не дублируются вручную внутри компонентов.
const EXERCISE_CATALOG: readonly SwimExercise[] = [
  {
    id: "freestyle",
    name: "Freestyle",
    description: "Вольный стиль — базовый стиль программы, равномерный гребок и ровное дыхание.",
    category: "stroke",
    stroke: "freestyle",
    equipment: [],
    difficulty: "beginner",
    primaryMuscles: ["широчайшие", "плечи", "кор"],
    secondaryMuscles: ["трицепс", "квадрицепс"],
    tags: ["базовый", "техника"],
    futureVideoId: null,
  },
  {
    id: "backstroke",
    name: "Backstroke",
    description: "На спине — открытое дыхание, работа над балансом тела и вращением корпуса.",
    category: "stroke",
    stroke: "backstroke",
    equipment: [],
    difficulty: "intermediate",
    primaryMuscles: ["широчайшие", "плечи"],
    secondaryMuscles: ["кор", "ягодицы"],
    tags: ["баланс", "техника"],
    futureVideoId: null,
  },
  {
    id: "kick",
    name: "Kick",
    description: "Работа ног с доской — развивает удержание позиции тела и силу ног.",
    category: "kick",
    stroke: "kick",
    equipment: ["доска"],
    difficulty: "beginner",
    primaryMuscles: ["квадрицепс", "икры"],
    secondaryMuscles: ["кор"],
    tags: ["ноги", "выносливость"],
    futureVideoId: null,
  },
  {
    id: "pull",
    name: "Pull",
    description: "Тяга с колобашкой — изолирует работу рук и корпуса, ноги почти не участвуют.",
    category: "pull",
    stroke: "freestyle",
    equipment: ["колобашка", "лопатки"],
    difficulty: "intermediate",
    primaryMuscles: ["широчайшие", "плечи"],
    secondaryMuscles: ["трицепс"],
    tags: ["руки", "сила"],
    futureVideoId: null,
  },
  {
    id: "catch-up",
    name: "Catch-up",
    description: "Одна рука ждёт впереди, пока другая завершает цикл — удлиняет гребок и учит терпению в воде.",
    category: "drill",
    stroke: "drill",
    equipment: [],
    difficulty: "beginner",
    primaryMuscles: ["плечи"],
    secondaryMuscles: ["кор"],
    tags: ["техника", "drill"],
    futureVideoId: null,
  },
  {
    id: "single-arm",
    name: "Single Arm",
    description: "Плавание одной рукой — вторая вытянута вперёд или у бедра, фокус на симметрии гребка.",
    category: "drill",
    stroke: "drill",
    equipment: [],
    difficulty: "intermediate",
    primaryMuscles: ["плечи", "широчайшие"],
    secondaryMuscles: ["кор"],
    tags: ["техника", "drill"],
    futureVideoId: null,
  },
  {
    id: "sculling",
    name: "Sculling",
    description: "Мелкие движения кистями у поверхности — развивает чувство опоры о воду.",
    category: "technique",
    stroke: "drill",
    equipment: [],
    difficulty: "advanced",
    primaryMuscles: ["предплечья", "плечи"],
    secondaryMuscles: [],
    tags: ["техника", "чувство воды"],
    futureVideoId: null,
  },
  {
    id: "6-1-6",
    name: "6-1-6",
    description: "6 ударов ногами на боку, 1 гребок, снова 6 ударов — учит вращению корпуса и балансу.",
    category: "drill",
    stroke: "drill",
    equipment: [],
    difficulty: "intermediate",
    primaryMuscles: ["кор"],
    secondaryMuscles: ["квадрицепс"],
    tags: ["баланс", "drill"],
    futureVideoId: null,
  },
  {
    id: "fingertip-drag",
    name: "Fingertip Drag",
    description: "Пальцы скользят по поверхности воды во время проноса руки — поднимает локоть, убирает провисание.",
    category: "drill",
    stroke: "drill",
    equipment: [],
    difficulty: "beginner",
    primaryMuscles: ["плечи"],
    secondaryMuscles: [],
    tags: ["техника", "drill"],
    futureVideoId: null,
  },
  {
    id: "easy-swim",
    name: "Easy Swim",
    description: "Свободное плавание в спокойном темпе — восстановление между интенсивными блоками.",
    category: "stroke",
    stroke: "mixed",
    equipment: [],
    difficulty: "beginner",
    primaryMuscles: [],
    secondaryMuscles: [],
    tags: ["восстановление"],
    futureVideoId: null,
  },
  {
    id: "drill",
    name: "Drill",
    description: "Общее техническое упражнение — конкретная задача уточняется в описании интервала.",
    category: "technique",
    stroke: "drill",
    equipment: [],
    difficulty: "beginner",
    primaryMuscles: [],
    secondaryMuscles: [],
    tags: ["техника", "drill"],
    futureVideoId: null,
  },
];

export function listExercises(): readonly SwimExercise[] {
  return EXERCISE_CATALOG;
}

export function getExerciseById(id: string): SwimExercise | null {
  return EXERCISE_CATALOG.find((exercise) => exercise.id === id) ?? null;
}

const EXERCISE_LABELS_RU: Readonly<Record<string, string>> = {
  freestyle: "Кроль",
  backstroke: "Кроль на спине",
  kick: "Работа ног",
  pull: "Тяга руками",
  "catch-up": "Догоняющий кроль",
  "single-arm": "Кроль одной рукой",
  sculling: "Скаллинг",
  "6-1-6": "6–1–6",
  "fingertip-drag": "Пронос пальцев по воде",
  "easy-swim": "Лёгкое плавание",
  drill: "Техническое упражнение",
};

// UI-перевод отделён от name: name входит в сохранённый snapshot/planKey.
export function exerciseLabelRu(id: string): string {
  return EXERCISE_LABELS_RU[id] ?? getExerciseById(id)?.name ?? id;
}
