import { env } from "cloudflare:workers";

async function init(){
 const db=env.DB;
 await db.batch([
  db.prepare("CREATE TABLE IF NOT EXISTS profile (id INTEGER PRIMARY KEY, name TEXT NOT NULL DEFAULT 'Илья', height REAL NOT NULL DEFAULT 167, start_weight REAL NOT NULL DEFAULT 86, target_weight REAL NOT NULL DEFAULT 67, program_start TEXT NOT NULL DEFAULT '2026-07-21', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),
  db.prepare("CREATE TABLE IF NOT EXISTS workout_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, completed TEXT NOT NULL DEFAULT '[]', rounds INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),
  db.prepare("CREATE TABLE IF NOT EXISTS measurements (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, weight REAL, waist REAL, chest REAL, biceps REAL, thigh REAL, neck REAL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),
  db.prepare("CREATE TABLE IF NOT EXISTS photos (id INTEGER PRIMARY KEY AUTOINCREMENT, object_key TEXT NOT NULL, date TEXT NOT NULL, content_type TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),
  db.prepare("CREATE TABLE IF NOT EXISTS daily_activity (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL UNIQUE, steps INTEGER NOT NULL DEFAULT 0, active_minutes INTEGER NOT NULL DEFAULT 0, calories INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),
  db.prepare("INSERT OR IGNORE INTO profile (id,name,height,start_weight,target_weight,program_start) VALUES (1,'Илья',167,86,67,'2026-07-21')"),
  db.prepare("INSERT OR IGNORE INTO workout_logs (id,date,type,title,completed,rounds) VALUES (1,'2026-07-21','Силовая','Гантели по кругу','[]',2)"),
  db.prepare("INSERT OR IGNORE INTO measurements (id,date,weight) VALUES (1,'2026-07-21',85.9)")
 ]);
}
export async function GET(){await init();const db=env.DB;const [p,w,m,ph,a]=await Promise.all([db.prepare("SELECT id,name,height,start_weight startWeight,target_weight targetWeight,program_start programStart FROM profile WHERE id=1").first(),db.prepare("SELECT * FROM workout_logs ORDER BY date DESC,id DESC").all(),db.prepare("SELECT * FROM measurements ORDER BY date DESC,id DESC").all(),db.prepare("SELECT id,date,created_at createdAt FROM photos ORDER BY created_at ASC,id ASC").all(),db.prepare("SELECT id,date,steps,active_minutes activeMinutes,calories FROM daily_activity ORDER BY date DESC").all()]);return Response.json({profile:p,workouts:w.results,measurements:m.results,activity:a.results,photos:ph.results.map((x:any)=>({...x,url:`/api/photos?id=${x.id}`}))});}
export async function POST(req:Request){await init();const db=env.DB;const b:any=await req.json();if(b.action==="profile"){await db.prepare("UPDATE profile SET name=?,height=?,start_weight=?,target_weight=? WHERE id=1").bind(b.name,b.height,b.startWeight,b.targetWeight).run()}else if(b.action==="measurement"){await db.prepare("INSERT INTO measurements (date,weight,waist,chest,biceps,thigh,neck) VALUES (?,?,?,?,?,?,?)").bind(b.date,b.weight||null,b.waist||null,b.chest||null,b.biceps||null,b.thigh||null,b.neck||null).run()}else if(b.action==="workout"){await db.prepare("INSERT INTO workout_logs (date,type,title,completed,rounds) VALUES (?,?,?,?,?)").bind(b.date,b.type,b.title,JSON.stringify(b.completed),b.rounds).run()}else if(b.action==="activity"){await db.prepare("INSERT INTO daily_activity (date,steps,active_minutes,calories) VALUES (?,?,?,?) ON CONFLICT(date) DO UPDATE SET steps=excluded.steps,active_minutes=excluded.active_minutes,calories=excluded.calories").bind(b.date,Number(b.steps)||0,Number(b.activeMinutes)||0,Number(b.calories)||0).run()}else return Response.json({error:"Unknown action"},{status:400});return Response.json({ok:true});}
